import streamlit as st
import pandas as pd
from src.utils.helpers import inject_premium_css, render_metric_card
from src.insights.insight_generator import generate_automated_insights
from src.kpi.kpi_engine import identify_kpi_columns
from src.anomaly_detection.anomaly_detector import detect_anomalies_zscore
from src.reports.report_generator import generate_html_report

st.set_page_config(page_title="Business Insights Portal", page_icon="💡", layout="wide")
inject_premium_css()

st.title("💡 Business Insights & Executive Reports")
st.markdown("---")

df = st.session_state.get("df")

if df is None:
    st.warning("⚠️ Please load a dataset first by navigating to the home page or uploading in the sidebar.")
else:
    # 2 Columns: Insights Narrative & Anomalies/Report Download
    icol1, icol2 = st.columns([2, 1])
    
    # Identify kpis
    kpis = identify_kpi_columns(df)
    primary_metric = kpis["metric_columns"][0] if kpis["metric_columns"] else None
    
    with icol1:
        st.markdown("### Automated Business Insights")
        st.markdown("Synthesized analytical evaluations generated by scanning dataset rows, dimensions, and anomalies.")
        
        with st.spinner("Synthesizing metrics and trends..."):
            insights = generate_automated_insights(df)
            
        for ins in insights:
            # Display colored alert callouts
            if ins["type"] == "warning":
                st.warning(f"**{ins['title']}**\n\n{ins['description']}")
            elif ins["type"] == "success":
                st.success(f"**{ins['title']}**\n\n{ins['description']}")
            else:
                st.info(f"**{ins['title']}**\n\n{ins['description']}")
                
        # Strategic Recommendations Section
        st.markdown("### 🎯 Strategic Business Recommendations")
        st.markdown("""
        Based on the current trends and segment drivers:
        - **Leverage Core Growth Channels:** Identify highest volume categories and allocate marketing/resource bandwidth to maximize ROI.
        - **Investigate Outliers:** Inspect anomalies flagged during metric calculation to detect system billing faults or sudden peak events.
        - **Maintain Data Completeness:** Periodic data synchronization ensures quality scores remain high and prediction accuracy is stable.
        """)
        
    with icol2:
        st.markdown("### Executive Report Exporter")
        st.markdown("Download a printable, self-contained BI briefing report containing these insights, tables, and statistics.")
        
        # Report compiler
        try:
            anoms = detect_anomalies_zscore(df, primary_metric) if primary_metric else None
            # Generate summary config
            from src.profiling.data_profiler import profile_dataset
            profile = profile_dataset(df)
            
            report_html = generate_html_report(
                dataset_name=st.session_state.filename or "dataset",
                profile_summary=profile,
                insights=insights,
                anomalies_df=anoms
            )
            
            st.download_button(
                label="📥 Download Executive PDF/HTML Briefing",
                data=report_html,
                file_name=f"executive_briefing_{st.session_state.filename.split('.')[0] if st.session_state.filename else 'report'}.html",
                mime="text/html",
                use_container_width=True
            )
            st.success("Briefing compiled successfully. Ready for download!")
        except Exception as e:
            st.error(f"Could not construct report document: {str(e)}")
            
        st.markdown("---")
        
        # Anomaly highlights in sidebar-column
        st.markdown("### 🔔 Outlier Flags")
        if primary_metric:
            anoms = detect_anomalies_zscore(df, primary_metric)
            if not anoms.empty:
                st.markdown(f"Detected **{len(anoms)} anomalies** in primary metric `{primary_metric}`:")
                for idx, row in anoms.head(5).iterrows():
                    st.error(f"**Row {idx + 1}**: {row['anomaly_reason']}")
                if len(anoms) > 5:
                    st.caption(f"And {len(anoms) - 5} other flagged records.")
            else:
                st.success("No anomalies detected in primary metric.")
        else:
            st.caption("No active numerical metric columns to check outliers.")
pocket = str
